POST http://172.17.1.126:3420/tst123/123123/1adf

<?xml version="1.0"?>
<MXP_DemandUpdate_Request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ns0:RecordSet xmlns:ns0="urn:synergy55.com:mxp:mm:demandupdate">
		<ns0:SourceSys>MXP-US</ns0:SourceSys>
		<ns0:Salesordernumber>6843568</ns0:Salesordernumber>
		<ns0:Salesorderlineitem>1</ns0:Salesorderlineitem>
		<ns0:Shiptoparty>Nautique Boat Company, Inc</ns0:Shiptoparty>
		<ns0:Materialnumber>679758</ns0:Materialnumber>
		<ns0:Plant>1230</ns0:Plant>
		<ns0:Openorderquantity>1.0</ns0:Openorderquantity>
		<ns0:Unitofmeasure>RO</ns0:Unitofmeasure>
		<ns0:Requirementdate>2019-05-14</ns0:Requirementdate>
		<ns0:Mxprecordstatus>open</ns0:Mxprecordstatus>
	</ns0:RecordSet>
	<ns0:RecordSet xmlns:ns0="urn:synergy55.com:mxp:mm:demandupdate">
		<ns0:SourceSys>MXP-US</ns0:SourceSys>
		<ns0:Salesordernumber>6843568</ns0:Salesordernumber>
		<ns0:Salesorderlineitem>2</ns0:Salesorderlineitem>
		<ns0:Shiptoparty>Nautique Boat Company, Inc</ns0:Shiptoparty>
		<ns0:Materialnumber>676137</ns0:Materialnumber>
		<ns0:Plant>1230</ns0:Plant>
		<ns0:Openorderquantity>3.0</ns0:Openorderquantity>
		<ns0:Unitofmeasure>RO</ns0:Unitofmeasure>
		<ns0:Requirementdate>2019-05-14</ns0:Requirementdate>
		<ns0:Mxprecordstatus>open</ns0:Mxprecordstatus>
	</ns0:RecordSet>
</MXP_DemandUpdate_Request>

POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/demand
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0"?>
<MXP_DemandUpdate_Request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ns0:RecordSet xmlns:ns0="urn:synergy55.com:mxp:mm:demandupdate">
		<ns0:SourceSys>MXP-US</ns0:SourceSys>
		<ns0:Salesordernumber>6843568</ns0:Salesordernumber>
		<ns0:Salesorderlineitem>1</ns0:Salesorderlineitem>
		<ns0:Shiptoparty>Nautique Boat Company, Inc</ns0:Shiptoparty>
		<ns0:Materialnumber>679758</ns0:Materialnumber>
		<ns0:Plant>1230</ns0:Plant>
		<ns0:Openorderquantity>1.0</ns0:Openorderquantity>
		<ns0:Unitofmeasure>RO</ns0:Unitofmeasure>
		<ns0:Requirementdate>2019-05-14</ns0:Requirementdate>
		<ns0:Mxprecordstatus>open</ns0:Mxprecordstatus>
	</ns0:RecordSet>
	<ns0:RecordSet xmlns:ns0="urn:synergy55.com:mxp:mm:demandupdate">
		<ns0:SourceSys>MXP-US</ns0:SourceSys>
		<ns0:Salesordernumber>6843568</ns0:Salesordernumber>
		<ns0:Salesorderlineitem>2</ns0:Salesorderlineitem>
		<ns0:Shiptoparty>Nautique Boat Company, Inc</ns0:Shiptoparty>
		<ns0:Materialnumber>676137</ns0:Materialnumber>
		<ns0:Plant>1230</ns0:Plant>
		<ns0:Openorderquantity>3.0</ns0:Openorderquantity>
		<ns0:Unitofmeasure>RO</ns0:Unitofmeasure>
		<ns0:Requirementdate>2019-05-14</ns0:Requirementdate>
		<ns0:Mxprecordstatus>open</ns0:Mxprecordstatus>
	</ns0:RecordSet>
</MXP_DemandUpdate_Request>



POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/api/consumption
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<InvoiceLineRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <s0:InvoiceLine xmlns:s0="urn:synergy55.com:mxp:btr:consumption">
      <s0:source>ANAND</s0:source>
      <s0:createdate>2019-03-22</s0:createdate>
      <s0:document>6562792</s0:document>
      <s0:linetype>LINE</s0:linetype>
      <s0:docline>1</s0:docline>
      <s0:ordersource>mxq</s0:ordersource>
      <s0:dropship>false</s0:dropship>
      <s0:DC>LD</s0:DC>
      <s0:whs>LD</s0:whs>
      <s0:salesarea>South Gulf Coast</s0:salesarea>
      <s0:rep>0880</s0:rep>
      <s0:repname>Tom Hanna</s0:repname>
      <s0:cust>6013400</s0:cust>
      <s0:custname>Nautique Boat Company, Inc</s0:custname>
      <s0:assignstrata>10</s0:assignstrata>
      <s0:calcstrata>10</s0:calcstrata>
      <s0:shipvia>C-1</s0:shipvia>
      <s0:shipcust>6013405</s0:shipcust>
      <s0:shipname>Nautique Boat Company, Inc</s0:shipname>
      <s0:shipaddress>Lamination 14700 Aerospace Parkway</s0:shipaddress>
      <s0:shipcity>Orlando</s0:shipcity>
      <s0:shipstate>FL</s0:shipstate>
      <s0:shipzip>32832</s0:shipzip>
      <s0:shipcountry>US</s0:shipcountry>
      <s0:legacyitem>655191</s0:legacyitem>
      <s0:itemdescription>GUM M100 12.7MM 1/2 VIC1+PH 44.5 X 44.5 24SH/CT 330SF/CT</s0:itemdescription>
      <s0:vendor>Gurit U S A</s0:vendor>
      <s0:productgroup>OFV</s0:productgroup>
      <s0:prGroupSummary>Core</s0:prGroupSummary>
      <s0:biztype>Core / Chemicals</s0:biztype>
      <s0:shippedqty>990.0</s0:shippedqty>
      <s0:UOM>SF</s0:UOM>
      <s0:shippedweight>297.0</s0:shippedweight>
      <s0:salesprice>3.98</s0:salesprice>
      <s0:PriceSource>cf</s0:PriceSource>
      <s0:freightadder>0.0</s0:freightadder>
      <s0:materialcost>3.37992</s0:materialcost>
      <s0:salesamt>3940.2</s0:salesamt>
      <s0:taxamount>0.0</s0:taxamount>
      <s0:addlcharge />
      <s0:addlamount>0.0</s0:addlamount>
      <s0:currency>USD</s0:currency>
      <s0:conversionrate>1.0</s0:conversionrate>
      <s0:creditreason />
      <s0:market>Open Molding</s0:market>
      <s0:segment>Marine</s0:segment>
      <s0:shipdate>2019-03-22</s0:shipdate>
      <s0:warehouseName>Lakeland</s0:warehouseName>
      <s0:DCName>Lakeland</s0:DCName>
      <s0:marginamt>594.08</s0:marginamt>
      <s0:MATNR>655191</s0:MATNR>
      <s0:MATKL>12312</s0:MATKL>
      <s0:WERKS>12312</s0:WERKS>
   </s0:InvoiceLine>
</InvoiceLineRequest>


POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/inventorymovement/Q41CLNT421
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<InventoryMovementRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <s0:InventoryMovement xmlns:s0="urn:synergy55.com:mxp:dts:inventory">
        <s0:PSTNG_DATE>2019-03-12</s0:PSTNG_DATE>
        <s0:REF_DOC_NO/>
        <s0:GOODSMVT_CODE>03</s0:GOODSMVT_CODE>
        <s0:MATERIAL>23172</s0:MATERIAL>
        <s0:PLANT>1380</s0:PLANT>
        <s0:STGE_LOC>E002</s0:STGE_LOC>
        <s0:BATCH>INTERIM</s0:BATCH>
        <s0:MOVE_TYPE>562</s0:MOVE_TYPE>
        <s0:PO_NUMBER>0</s0:PO_NUMBER>
        <s0:PO_ITEM>0</s0:PO_ITEM>
        <s0:ENTRY_QNT>1536.0</s0:ENTRY_QNT>
        <s0:ENTRY_UOM_ISO>LBR</s0:ENTRY_UOM_ISO>
        <s0:MVT_IND/>
        <s0:MOVE_MAT/>
        <s0:MOVE_PLANT/>
        <s0:MOVE_STLOC/>
        <s0:EXPIRYDATE />
        <s0:MOVE_REAS/>
        <s0:SPEC_STOCK/>
        <s0:VENDOR/>
    </s0:InventoryMovement>
</InventoryMovementRequest>


POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/materialstatus/D41CLNT201
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0"?>
<MaterialStatusRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <RecordSet>
        <PLANT>1350</PLANT>
        <MATERIAL>000000000000216896</MATERIAL>
        <PUR_STATUS>20</PUR_STATUS>
    </RecordSet>
</MaterialStatusRequest>

<?xml version="1.0" encoding="UTF-8"?>
<MaterialStatusRequest>
    <RecordSet>
        <PLANT>1230</PLANT>
        <PUR_STATUS></PUR_STATUS>
        <MATERIAL>000000000000300831</MATERIAL>
    </RecordSet>
</MaterialStatusRequest>

<?xml version="1.0" encoding="UTF-8"?>
<MaterialStatusRequest>
    <RecordSet>
        <PLANT>1150</PLANT>
        <PUR_STATUS>10</PUR_STATUS>
        <MATERIAL>000000000000001024</MATERIAL>
    </RecordSet>
</MaterialStatusRequest>

<?xml version="1.0" encoding="UTF-8"?>
<ns0:MaterialStatusRequest xmlns:ns0="urn:synergy55.com:mxp:stp:materialstatus">
   <ns0:RecordSet>
      <ns0:PUR_STATUS>3234234234</ns0:PUR_STATUS>
      <ns0:STORAGE_LOCATION></ns0:STORAGE_LOCATION>
      <ns0:PLANT>10</ns0:PLANT>
      <ns0:MATERIAL>000000000000300831</ns0:MATERIAL>
   </ns0:RecordSet>
</ns0:MaterialStatusRequest>



<?xml version="1.0" encoding="UTF-8"?>
<n0:MaterialStatusRequest xmlns:n0="urn:synergy55.com:mxp:stp:materialstatus">
    <n0:RecordSet>
        <n0:PLANT>3234234234</n0:PLANT>
        <n0:PUR_STATUS>10</n0:PUR_STATUS>
        <n0:MATERIAL>000000000000300831</n0:MATERIAL>
    </n0:RecordSet>
</n0:MaterialStatusRequest>


POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/inventoryaging/D41CLNT201
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<InventoryAgingRequest>
   <InventoryAging>
      <asofdate>2019-05-30</asofdate>
      <type>I</type>
      <inentity>INV</inentity>
      <itemno>0001</itemno>
      <warehouse>WH</warehouse>
      <period>05</period>
      <year>2019</year>
      <uom>LB</uom>
      <cost>10</cost>
      <qtyonhand>10</qtyonhand>
      <qty0to31>31</qty0to31>
      <qty31to60>60</qty31to60>
      <qty61to90>90</qty61to90>
      <qty91to120>120</qty91to120>
      <qty121to150>151</qty121to150>
      <qty151to180>181</qty151to180>
      <qty181to270>271</qty181to270>
      <qty271to360>361</qty271to360>
      <qty361to450>451</qty361to450>
      <qty451to540>541</qty451to540>
      <qty541to720>721</qty541to720>
      <qty721plus>720</qty721plus>
      <maxdays>40</maxdays>
      <amtonhand>10</amtonhand>
      <amt0to30>30</amt0to30>
      <amt31to60>60</amt31to60>
      <amt61to90>91</amt61to90>
      <amt91to120>121</amt91to120>
      <amt121to150>151</amt121to150>
      <amt151to180>181</amt151to180>
      <amt181to270>271</amt181to270>
      <amt271to360>361</amt271to360>
      <amt361to450>451</amt361to450>
      <amt451to540>541</amt451to540>
      <amt541to630>631</amt541to630>
      <amt631to720>721</amt631to720>
      <amt721plus>720</amt721plus>
      <lohu>10</lohu>
   </InventoryAging>
</InventoryAgingRequest>

POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/inventorymovement/
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<InventoryMovementRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <n0:InventoryMovement xmlns:n0="urn:synergy55.com:mxp:dts:inventory">
  <n0:PSTNG_DATE>1999-01-24</n0:PSTNG_DATE>
  <n0:REF_DOC_NO>String 1</n0:REF_DOC_NO>
  <n0:GOODSMVT_CODE>2</n0:GOODSMVT_CODE>
  <n0:MATERIAL>3</n0:MATERIAL>
  <n0:PLANT>4</n0:PLANT>
  <n0:STGE_LOC>String 5</n0:STGE_LOC>
  <n0:BATCH>String 6</n0:BATCH>
  <n0:MOVE_TYPE>7</n0:MOVE_TYPE>
  <n0:PO_NUMBER>8</n0:PO_NUMBER>
  <n0:PO_ITEM>9</n0:PO_ITEM>
  <n0:ENTRY_QNT>0.10E-13</n0:ENTRY_QNT>
  <n0:ENTRY_UOM_ISO>String 12</n0:ENTRY_UOM_ISO>
  <n0:MVT_IND>String 13</n0:MVT_IND>
  <n0:MOVE_MAT>String 14</n0:MOVE_MAT>
  <n0:MOVE_PLANT>String 15</n0:MOVE_PLANT>
  <n0:MOVE_STLOC>String 16</n0:MOVE_STLOC>
  <n0:EXPIRYDATE>String 17</n0:EXPIRYDATE>
  <n0:MOVE_REAS>String 18</n0:MOVE_REAS>
  <n0:SPEC_STOCK>String 19</n0:SPEC_STOCK>
  <n0:VENDOR>String 20</n0:VENDOR>
 </n0:InventoryMovement>
 <n0:InventoryMovement xmlns:n0="urn:synergy55.com:mxp:dts:inventory">
  <n0:PSTNG_DATE>1999-01-24</n0:PSTNG_DATE>
  <n0:REF_DOC_NO>String 21</n0:REF_DOC_NO>
  <n0:GOODSMVT_CODE>22</n0:GOODSMVT_CODE>
  <n0:MATERIAL>23</n0:MATERIAL>
  <n0:PLANT>24</n0:PLANT>
  <n0:STGE_LOC>String 25</n0:STGE_LOC>
  <n0:BATCH>String 26</n0:BATCH>
  <n0:MOVE_TYPE>27</n0:MOVE_TYPE>
  <n0:PO_NUMBER>28</n0:PO_NUMBER>
  <n0:PO_ITEM>29</n0:PO_ITEM>
  <n0:ENTRY_QNT>0.30E-13</n0:ENTRY_QNT>
  <n0:ENTRY_UOM_ISO>String 32</n0:ENTRY_UOM_ISO>
  <n0:MVT_IND>String 33</n0:MVT_IND>
  <n0:MOVE_MAT>String 34</n0:MOVE_MAT>
  <n0:MOVE_PLANT>String 35</n0:MOVE_PLANT>
  <n0:MOVE_STLOC>String 36</n0:MOVE_STLOC>
  <n0:EXPIRYDATE>String 37</n0:EXPIRYDATE>
  <n0:MOVE_REAS>String 38</n0:MOVE_REAS>
  <n0:SPEC_STOCK>String 39</n0:SPEC_STOCK>
  <n0:VENDOR>String 40</n0:VENDOR>
 </n0:InventoryMovement>
</InventoryMovementRequest>

POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/coaupdate/D41CLNT201
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml; encoding=utf-8;

this is a? asdfer a9? asdfadsf .a asdf a9! asdf asdf? Awasdf a! a.sdf. sfasdf .
<?xml version="1.0"?>
<n0:MXP_COARequest xmlns:n0="urn:synergy55.com:mxp:stp:coaupdate">
    <n0:RecordSet>
        <n0:MATNR>000000000000216896</n0:MATNR>
        <n0:LIFNR>22323</n0:LIFNR>
        <n0:WERKS/>
        <n0:CHARG/>
        <n0:URZTP>1</n0:URZTP>
    </n0:RecordSet>
</n0:MXP_COARequest>

POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/realtimegl/D41CLNT201
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0"?>
<MXP_RealtimeGL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RecordSet>
    <DOC_TYPE>ZM</DOC_TYPE>
    <COMP_CODE>1510</COMP_CODE>
    <ACC_PRINCIPLE/>
    <REF_DOC_NO>lauratst</REF_DOC_NO>
    <DOC_DATE>2019-06-12</DOC_DATE>
    <PSTNG_DATE>2019-06-13</PSTNG_DATE>
    <HEADER_TXT>Laura Test GL Entry Push</HEADER_TXT>
    <item>
      <ITEMNO_ACC>0000000001</ITEMNO_ACC>
      <GL_ACCOUNT>0000610000</GL_ACCOUNT>
      <COMP_CODE>1510</COMP_CODE>
      <ITEM_TEXT/>
      <COSTCENTER/>
      <PROFIT_CTR>PCNANA</PROFIT_CTR>
      <AMOUNT>-777.77</AMOUNT>
      <CURRENCY>USD</CURRENCY>
    </item>
    <item>
      <ITEMNO_ACC>0000000002</ITEMNO_ACC>
      <GL_ACCOUNT>0000899999</GL_ACCOUNT>
      <COMP_CODE>1510</COMP_CODE>
      <ITEM_TEXT/>
      <COSTCENTER/>
      <PROFIT_CTR>PCNANA</PROFIT_CTR>
      <AMOUNT>777.77</AMOUNT>
      <CURRENCY>USD</CURRENCY>
    </item>
  </RecordSet>
</MXP_RealtimeGL>

fbl1n
fb03

POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/payable/D41CLNT201
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0"?>
<MXP_Payable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RecordSet>
    <DOC_TYPE>ZC</DOC_TYPE>
    <COMP_CODE>1510</COMP_CODE>
    <REF_DOC_NO>980057388</REF_DOC_NO>
    <DOC_DATE>2019-05-15</DOC_DATE>
    <PSTNG_DATE>2019-06-18</PSTNG_DATE>
    <HEADER_TXT>1968011</HEADER_TXT>
    <AccountGL>
      <ITEMNO_ACC>0000000001</ITEMNO_ACC>
      <GL_ACCOUNT>0000610000</GL_ACCOUNT>
    </AccountGL>
    <AccountPayable>
      <ITEMNO_ACC>0000000002</ITEMNO_ACC>
      <VENDOR_CODE>0000750000</VENDOR_CODE>
    </AccountPayable>
    <item>
      <ITEMNO_ACC>0000000001</ITEMNO_ACC>
      <AMOUNT>117.76</AMOUNT>
      <CURRENCY>USD</CURRENCY>
    </item>
    <item>
      <ITEMNO_ACC>0000000002</ITEMNO_ACC>
      <AMOUNT>-117.76</AMOUNT>
      <CURRENCY>USD</CURRENCY>
    </item>
  </RecordSet>
</MXP_Payable>

<?xml version="1.0"?>
<MXP_Payable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RecordSet>  
    <DOC_TYPE>ZC</DOC_TYPE>    
    <COMP_CODE>1510</COMP_CODE> 
    <REF_DOC_NO>lauratst</REF_DOC_NO>   
    <DOC_DATE>2019-06-12</DOC_DATE>   
    <PSTNG_DATE>2019-06-13</PSTNG_DATE>    
    <HEADER_TXT>Laura Test AP Push</HEADER_TXT> 
    <AccountGL>
      <ITEMNO_ACC>0000000001</ITEMNO_ACC>
      <GL_ACCOUNT>0000610000</GL_ACCOUNT>
    </AccountGL>
    <AccountPayable>
      <ITEMNO_ACC>0000000002</ITEMNO_ACC>
      <VENDOR_CODE>750000</VENDOR_CODE>      
    </AccountPayable>
    <item>
      <ITEMNO_ACC>0000000001</ITEMNO_ACC>
      <AMOUNT>777.77</AMOUNT>
      <CURRENCY>USD</CURRENCY>
    </item>
    <item>
      <ITEMNO_ACC>0000000002</ITEMNO_ACC>
      <AMOUNT>-777.77</AMOUNT>
      <CURRENCY>USD</CURRENCY>
    </item>
  </RecordSet>
</MXP_Payable>


POST http://s55-pomdl01.synergy55.com:50000/RESTAdapter/OCVendorInvoice/D41CLNT201
Authorization: Basic UE9fU0VSVklDRV9VU0VSOnJ3cjcwOGt0azA=
Content-Type: application/xml

<?xml version="1.0"?>
<X12_4000_810 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <BIG BIG04="1361128-00" BIG03="2019-01-09" BIG02="906230213" BIG01="2019-02-26"/>
  <N1Loop1>
    <N1 N102="COMPOSITES ONE" N101="ST"/>
    <N3 N301="4750 KISTER COURT"/>
    <N4 N403="440043928" N402="OH" N401="ASHTABULA"/>
  </N1Loop1>
  <N1Loop1>
    <N1 N102="Owens Corning Sales LLC" N101="RI"/>
    <N3 N301="62375 Collections Center Drive"/>
    <N4 N403="60693" N402="IL" N401="Chicago"/>
  </N1Loop1>
  <ITD ITD12="1% 15 Days, Net 30 Days" ITD08="398.20" ITD06="2019-03-28" ITD04="2019-03-13" ITD02="1" ITD01="01"/>
  <DTM DTM02="2019-02-26" DTM01="011"/>
  <IT1Loop1>
    <IT1 IT109="00000000000020232" IT108="CB" IT107="00621714" IT106="VN" IT104="2.06" IT103="LB" IT102="12832.892" IT101="10">
      <CTP CTP08="26435.76"/>
      <PIDLoop1>
        <PID_2 PID05="FM M8643 1.50 OZ 49.5" PID01="F"/>
      </PIDLoop1>
    </IT1>
  </IT1Loop1>
  <IT1Loop1>
    <IT1 IT109="" IT108="" IT107="00391951" IT106="VN" IT104="2.06" IT103="LB" IT102="6496.914" IT101="20">
      <CTP CTP08="13383.64"/>
      <PIDLoop1>
        <PID_2 PID05="FM M8643 1.50 OZ 49.5" PID01="F"/>
      </PIDLoop1>
    </IT1>
  </IT1Loop1>
  <TDS TDS04="398.20" TDS03="39421.20" TDS02="39819.40" TDS01="39819.40"/>
  <SACLoop2>
    <SAC_3 SAC15="Prepaid Freight" SAC12="ZZ" SAC05="439.95" SAC02="D240" SAC01="N"/>
  </SACLoop2>
  <CTT CTT01="2"/>
</X12_4000_810>


POST https://dev.s4h.synergy55.com:44302/sap/bw/ina/zzpricing?sap-client=200
Authorization: Basic YXJhdmluYTp3aW5kb3czMg==
Content-Type: application/json

{
  "sample" : "hello"
}


